### ISSUE TITLE
User Account

### ISSUE THREAD

**Issue by CellularGeek** [projectwife/tesitoo-opencart#120]
Logged-in user info is not shown on the user's dashboard. So it's hard for a user to see his account name or username from the Dashboard.

**Comment by david-r-edgar** [comment]
Do you mean logged in as buyer, or logged in as a farmer?

**Comment by CellularGeek** [comment]
Yes and it doesn't show any indication of the logged in user. Like displaying the name of the logged in person.

**Comment by david-r-edgar** [comment]
Yes, but for which type of account? Buyer or farmer?

**Comment by david-r-edgar** [comment]
The buyer's name is not indicated on the dashboard when they log in.
It should definitely be indicated prominently on https://tesitoo.com/index.php?route=account/account
We might even want to display their name in the top menu bar like many sites do.

**Comment by david-r-edgar** [comment]
The buyer's name is now shown on the top menu bar, next to the account menu icon (when the buyer is logged in).

The buyer's name is also shown on their dashboard. (My Account)
