### ISSUE TITLE
Email Unique

### ISSUE THREAD

**Issue by CellularGeek** [projectwife/tesitoo-opencart#121]
The Email addresses field cannot be a unique since farmers are going to be working in groups with a single admin, who will must probably have one email address for the entire group.

**Comment by david-r-edgar** [comment]
My understanding is that there was to be only one account for each group. The individual farmers wouldn't have their own accounts.
If this is correct, there's no problem with email being the unique id.

**Comment by CellularGeek** [comment]
Alright David, that makes a lot of sense

**Comment by david-r-edgar** [comment]
Discussed in a recent call, and we agreed that the assumption I stated above was correct - one account per group.
