### ISSUE TITLE
Warnings when editing order product status via API

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/tesitoo-opencart#123]
<b>Notice</b>: Undefined variable: subject in
<b>/var/www/api/v1/catalog/controller/vendor/order_product.php</b> on line
<b>129</b>
<b>Notice</b>: Error: E-Mail subject required! in
<b>/var/www/system/library/mail.php</b> on line
<b>76</b>

**Comment by kaizen10** [comment]
In the app, I'm hitting this issue when editing the order status for an order containing multiple products.

**Comment by david-r-edgar** [comment]
Actually I think the problem is because the status which is being set is not one of the expected values.
It's the same as #127.
If you try with a status 3, 5 or 7, it should be fine.

**Comment by david-r-edgar** [comment]
Added messages for default statuses in #130 7d4c9c4e1423b8db153a79101bf1d415a687ddcc.
