### ISSUE TITLE
Cart Checkout - If Terms and Conditions not checked - alert pops up, but then after checking box, cannot proceed

### ISSUE THREAD

**Issue by gwenpowers** [projectwife/tesitoo-opencart#206]
When purchasing a product, during checkout, if the Terms and Conditions Box is unchecked, in Step #5, the error message "Warning - You must agree to the Terms and Conditions" appears.  If the user then checks the Terms and Conditions box, the Continue button is not enabled (it stays on Loading...") and the user cannot proceed to the next step.  
This error was found under Guest Check Out.

**Comment by david-r-edgar** [comment]
Fixed in #207.
