### ISSUE TITLE
Error undefined when editing order as admin

### ISSUE THREAD

**Issue by gwenpowers** [projectwife/tesitoo-opencart#211]
Testitoo.com says: Error undefined
 When logged in as Admin and selecting product to edit - Error undefined. 
You can proceed but any changes receive the same error undefined and no changes are made.

**Comment by david-r-edgar** [comment]
Happens on tesitoo.com
Doesn't happen on local installation.

**Comment by david-r-edgar** [comment]
admin/view/template/sale/order_form.tpl is requesting several api resources over http, not https.
This causes the alert (and a console error).

**Comment by david-r-edgar** [comment]
#219 also necessary for the fix
